services:
  #################################################################
  # POSTGRES DATABASE
  #################################################################
  postgres:
    image: "${POSTGRES_IMAGE:-postgres:latest}"
    container_name: "postgres"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-zabbix}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-zabbix}"
      POSTGRES_DB: "${POSTGRES_DB:-zabbix}"
      PG_DATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - network-zabbix

  #################################################################
  # ZABBIX SERVER (PGSQL)
  #################################################################
  zabbix-server:
    image: "${ZABBIX_SERVER_IMAGE:-zabbix/zabbix-server-pgsql:ubuntu-7.2.1}"
    container_name: "zbx_server"
    restart: unless-stopped
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: "postgres"
      DB_SERVER_PORT: "5432"
      POSTGRES_USER: "${POSTGRES_USER:-zabbix}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-zabbix}"
      POSTGRES_DB: "${POSTGRES_DB:-zabbix}"
      # Si tu veux définir un fuseau horaire :
      # TZ: "${TZ:-UTC}"
    depends_on:
      - postgres
    networks:
      - network-zabbix

  #################################################################
  # ZABBIX FRONTEND (NGINX + PGSQL)
  #################################################################
  zabbix-frontend:
    image: "${ZABBIX_FRONTEND_IMAGE:-zabbix/zabbix-web-nginx-pgsql:ubuntu-7.2.1}"
    container_name: "zbx_frontend"
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      DB_SERVER_HOST: "postgres"
      POSTGRES_USER: "${POSTGRES_USER:-zabbix}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-zabbix}"
      POSTGRES_DB: "${POSTGRES_DB:-zabbix}"
      PHP_TZ: "${TZ:-UTC}"
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_SERVER_PORT: "10051"
    depends_on:
      - zabbix-server
    networks:
      - network-zabbix

  #################################################################
  # ZABBIX AGENT
  #################################################################
  zabbix-agent:
    image: "${ZABBIX_AGENT_IMAGE:-zabbix/zabbix-agent:ubuntu-7.2.1}"
    container_name: "zbx_agent"
    restart: unless-stopped
    ports:
      - "10050:10050"
    environment:
      ZBX_ACTIVE_ALLOW: "false"
      TZ: "${TZ:-UTC}"
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_SERVER_PORT: "10051"
      ZBX_HOSTNAME: "zbx_agent"
      ZBX_HOSTNAMEITEM: "system.hostname"
    depends_on:
      - zabbix-server
    networks:
      - network-zabbix

  #################################################################
  # GRAFANA
  #################################################################
  grafana:
    image: "${GRAFANA_IMAGE:-grafana/grafana:latest}"
    container_name: "grafana"
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "${GRAFANA_USER:-admin}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_SECRET:-adminpass}"
      GF_INSTALL_PLUGINS: "alexanderzobnin-zabbix-app"
      TZ: "${TZ:-UTC}"
    user: "472"
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - zabbix-frontend
    networks:
      - network-zabbix

volumes:
  postgres: {}
  grafana: {}

networks:
  network-zabbix:
    driver: bridge

